# Generated by Django 3.2.18 on 2023-04-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict4d', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='gender',
        ),
    ]
