# Generated by Django 3.2.18 on 2023-04-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict4d', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Malaria_case',
        ),
    ]
